version: "3"
services:
  hmpps-tier-to-delius-update:
    image: quay.io/hmpps/hmpps-tier-to-delius-update:latest
    container_name: hmpps-tier-to-delius-update
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - HMPPS_SQS_LOCALSTACKURL=http://localstack
  localstack:
    image: localstack/localstack:0.12.20
    networks:
      - hmpps
    container_name: hmpps-tier-to-delius-update-localstack
    ports:
      - "4566:4566"
      - 8999:8080
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
