spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

server:
  shutdown: immediate

aws:
  provider: localstack

sqs:
  endpoint:
    url: http://localhost:4576

community:
  endpoint:
    url: http://localhost:8091/secure
hmpps-tier:
  endpoint:
    url: http://localhost:8080/
oauth:
  endpoint:
    url: http://localhost:9090/auth
  client:
    id: hmpps-tier-to-delius-update
    secret: clientsecret


