spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

server:
  shutdown: immediate

aws:
  provider: localstack

sqs:
  endpoint.url: http://localhost:4576

community.endpoint.url: localhost:8082
hmpps-tier.endpoint.url: localhost:8081