spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

server:
  shutdown: immediate

hmpps.sqs:
  provider: localstack
  queues:
    tiercalculationqueue:
      dlqName: tier-calculation-queue-dl
      queueName: tier-calculation-queue
      subscribeTopicId: tiercalculationtopic
      subscribeFilter: '{"eventType":[ "TIER_CALCULATION_COMPLETE"] }'
  topics:
    tiercalculationtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

community:
  endpoint:
    url: http://localhost:8091/secure
hmpps-tier:
  endpoint:
    url: http://localhost:8080/
oauth:
  endpoint:
    url: http://localhost:9090/auth
  client:
    id: hmpps-tier-to-delius-update
    secret: clientsecret


